spring.application.name=notification-service-v2

server.port=8084

# Mail Properties
mail.producer=https://mailtrap.io/inboxes/3711711/messages
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=cca71eab06a1ba
spring.mail.password=92066db766abdd

#spring.mail.protocol=smtp

management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=product-service
management.tracing.sampling.probability=1.0

# -- Additional Configurations --
spring.config.import=optional:classpath:/application-kafka.properties

# Loki URL
loki.url=http://localhost:3100/loki/api/v1/push
