apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-order-service
  template:
    metadata:
      labels:
        app: mysql-order-service
    spec:
      containers:
        - image: mysql:8.3.0
          name: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mypassword
            - name: MYSQL_DATABASE
              value: order-db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 3307
  selector:
    app: mysql-order-service
