### GET product
GET http://localhost:8080/api/product
Content-Type: application/json

### creating product
POST http://localhost:8080/api/product
Content-Type: application/json

{
  "name": "Classic guitar YAMAHA C70",
  "description": "The Yamaha C70 guitar is the first step to learning this wonderful, complex and multifaceted instrument.",
  "price": 7300.00
}

### GET product
GET http://localhost:8083/api/product
Content-Type: application/json

### creating product
POST http://localhost:8083/api/product
Content-Type: application/json

{
  "name": "Classic guitar YAMAHA C70",
  "description": "The Yamaha C70 guitar is the first step to learning this wonderful, complex and multifaceted instrument.",
  "price": 7300.00
}
