apiVersion: v1
kind: Service
metadata:
  name: postgres-product-service
spec:
  selector:
    app: postgres-product
  ports:
    - protocol: TCP
      port: 5432       # внутренний порт PostgreSQL в контейнере
      targetPort: 5432
      nodePort: 35432   # внешний порт на ноде
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product
  template:
    metadata:
      labels:
        app: postgres-product
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: product-db
            - name: POSTGRES_USER
              value: userName
            - name: POSTGRES_PASSWORD
              value: secret
            - name: PGDATA
              value: /data/postgres
#          readinessProbe:
#            exec:
#              command:
#                - sh
#                - -c
#                - pg_isready -U userName -d product-db
#            initialDelaySeconds: 10
#            periodSeconds: 30
#            timeoutSeconds: 5
#            failureThreshold: 5
