# application-docker.properties inventory

spring.datasource.url=jdbc:postgresql://postgres-product:5432/product-db?serverTimezone=UTC
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

