spring.application.name=product-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5431/product-db?serverTimezone=UTC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=userName
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

#springdoc.swagger-ui.enabled=true
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.urls[0].name=Product Service
#springdoc.swagger-ui.urls[0].url=/aggregate/product-service/v3/api-docs
#springdoc.swagger-ui.urls[1].name=Order Service
#springdoc.swagger-ui.urls[1].url=/aggregate/order-service/v3/api-docs
#springdoc.swagger-ui.urls[2].name=Inventory Service
#springdoc.swagger-ui.urls[2].url=/aggregate/inventory-service/v3/api-docs
