spring.application.name=product-service

spring.datasource.url=jdbc:postgresql://localhost:5431/product-db?serverTimezone=UTC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=userName
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
