spring.application.name=product-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5431/product-db?serverTimezone=UTC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=userName
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=product-service
management.tracing.sampling.probability=1.0
