# application-docker.properties inventory

#spring.datasource.url=jdbc:postgresql://postgres-inventory:5432/inventory-db?serverTimezone=UTC
#eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

