apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: artemmakivskyy/product-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: userName
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres_user_password
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: LOKI_URL
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-product-service.default.svc.cluster.local:5432/product-db"
