### CREATE new user
POST http://localhost:8089/api/users
Content-Type: application/json

{
  "username": "artem",
  "address": {
    "city": "Kyiv",
    "street": "Main St"
  },
  "department": {
    "name": "Engineering"
  },
  "projects": [
    { "title": "CRM System" },
    { "title": "Internal Tools" }
  ],
  "tasks": [
    { "description": "Design architecture" },
    { "description": "Write tests" }
  ]
}


###

### GET all users
GET http://localhost:8089/api/users

###

### GET user by ID
GET http://localhost:8089/api/users/5

###

### UPDATE user by ID (замени id и тело на актуальные)
PUT http://localhost:8089/api/users/1
Content-Type: application/json

{
  "username": "updated_user",
  "address": {
    "city": "Lviv",
    "street": "Shevchenko Ave 10"
  },
  "department": {
    "id": 2
  },
  "projects": [
    { "id": 3 }
  ],
  "tasks": [
    {
      "description": "Updated task #1"
    }
  ]
}

###

### DELETE user by ID
DELETE http://localhost:8089/api/users/3
